import type { Metadata } from "next";
import { Inter,DM_Serif_Display  } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryProvider } from "@/react/query-provider";
import { auth } from "@clerk/nextjs/server";
import { createServices } from "@/modules/factory";
import { db } from "@/db/client";
import { UserProvider } from "@/react/users/context/user-provider";
import { GetUserSchema } from "@/shared/dto/users/get-user.dto";
import get_logger from "@/lib/logging/logger-factory";
import { ConfigurationError } from "@/exceptions/ConfigurationError";
export const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const fontDisplay = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-display",
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  const logger = get_logger();
  const user_auth = await auth();
  let user = null;

  if(user_auth.userId){
      const user_service = createServices(db).users;
      const data = await user_service.get_user(user_auth.userId);
      const res = GetUserSchema.safeParse({
        ...data,
        created_at: data.created_at.toISOString(),
        updated_at: data.updated_at.toISOString(),
      });
      if(!res.success){
        logger.error(
          res.error.message,
          {issues : res.error.issues},
        )
        throw new ConfigurationError(
          res.error.message,
          {issue: res.error.issues},
        )
      }
      user = res.data;
  }

  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fontDisplay.variable, "font-sans", inter.variable)}  
      suppressHydrationWarning
    >
      <QueryProvider>
        <ClerkProvider>
          <body 
          className="min-h-full flex flex-col"
          suppressHydrationWarning
          >
            <UserProvider user={user}>
              <TooltipProvider>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                  {children}
                  </ThemeProvider>
              </TooltipProvider>
            </UserProvider>
          </body>
        </ClerkProvider>
      </QueryProvider>
    </html>
  );
}
