import type { Metadata } from "next";
import { Inter,DM_Serif_Display  } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

export const inter = Inter({subsets:['latin'],variable:'--font-sans'});


export const fontDisplay = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-display",
  weight: "400",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", fontDisplay.variable, "font-sans", inter.variable)}  
      suppressHydrationWarning
    >
      <ClerkProvider>
        <body 
        className="min-h-full flex flex-col"
        suppressHydrationWarning
        >
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            {children}
            </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
