from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # Authentication & Authorization
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

    # Resource
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"

    # Business / Domain
    CONFLICT = "CONFLICT"
    INVALID_STATE = "INVALID_STATE"
    DOCUMENT_EXTRACTION_ERROR = "DOCUMENT_EXTRACTION_ERROR"
    MESSAGE_DESERIALIZATION_ERROR = "MESSAGE_DESERIALIZATION_ERROR"

    # Infrastructure
    DATABASE_ERROR = "DATABASE_ERROR"
    RTC_ERROR = "RTC_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"

    # Internal
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"

    # External Service
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    
    CACHE_MISS = "CACHE_MISS"